version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
      - aws s3 sync build/ s3://dev-env-map.airly.eu/map/ --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --exclude='*' --include='*.html' --acl public-read --sse --delete
      - aws s3 sync build/ s3://dev-env-map.airly.eu/map/ --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type application/javascript --exclude='*' --include='service-worker.js' --acl public-read --sse --delete
      - aws s3 sync build/ s3://dev-env-map.airly.eu/map/ --cache-control="max-age=604800,public" --exclude='*.html' --exclude='service-worker.js' --acl public-read --sse --delete
  post_build:
    commands:
      - cat /root/.npm/_logs/* || true
artifacts:
  files:
    - build/**/*
